apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: dev
  annotations: {}
  labels: {}
description: dev
gke:
  cluster: projects/elated-capsule-415713/locations/us-central/clusters/autopilot-cluster1

